apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: ai-task-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.ai-task.local

images:
  - name: docker.io/YOUR_DOCKERHUB/ai-task-backend
    newTag: staging
  - name: docker.io/YOUR_DOCKERHUB/ai-task-worker
    newTag: staging
  - name: docker.io/YOUR_DOCKERHUB/ai-task-frontend
    newTag: staging
