apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-task-config
data:
  MONGO_URI: mongodb://mongo:27017/aitask
  REDIS_URL: redis://redis:6379
  REDIS_STREAM_KEY: ai_tasks
  REDIS_GROUP: ai_task_workers
  NODE_ENV: production
  PORT: "4000"
